# Generated by Django 4.2.2 on 2023-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfigVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_config", models.CharField(max_length=150, unique=True)),
                ("days_maduration", models.PositiveIntegerField()),
                ("days_reproduction", models.PositiveIntegerField()),
                ("number_divisions", models.PositiveIntegerField()),
            ],
        ),
    ]
