# Generated by Django 4.2.2 on 2023-07-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bacterias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_lote", models.CharField()),
                ("array", models.JSONField()),
                ("status", models.BooleanField(default=False)),
                ("size", models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
