# Generated by Django 4.2.2 on 2023-07-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bacterias", "0005_lote_size_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="nivel_iter_end",
            field=models.CharField(default="0", max_length=4),
            preserve_default=False,
        ),
    ]
